# Generated by Django 3.2.6 on 2021-08-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_recieved',
            new_name='date_received',
        ),
    ]
