# Generated by Django 3.2.6 on 2021-08-24 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(default=' ', max_length=50)),
                ('serial_num', models.CharField(max_length=100, unique=True)),
                ('specification', models.TextField(default=' ')),
                ('date_received', models.DateField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplier')),
            ],
        ),
    ]
