# Generated by Django 3.2.6 on 2021-08-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210824_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='prod_name',
            field=models.CharField(choices=[('DESKTOP', 'DESKTOP'), ('KEYBOARD', 'KEYBOARD'), ('HDD', 'HDD'), ('SSD', 'SSD'), ('ROUTER', 'ROUTER'), ('MOUSE', 'MOUSE'), ('CPU', 'CPU'), ('LAPTOP', 'LAPTOP')], max_length=50),
        ),
    ]
