# Generated by Django 3.2.6 on 2021-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_stock_prod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='prod_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
