# Generated by Django 3.2.6 on 2021-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_stock_prod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
