# Generated by Django 3.2.6 on 2021-08-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_supplier_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='desk_num',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
